In [1]:
import os
os.chdir("/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age")
os.getcwd()

'/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age'

In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from src.data_collection import get_all_recent_tracks
from src.data_collection import get_track_info 
from src.data_cleaning import clean_track_info
from src.data_cleaning import clean_tracks
from src.data_collection import enrich_tracks

### First View

In [3]:
df= enrich_tracks("duzeniduzenadam",200,3)

Error, track not found: Bahadır Özgür-Dünyanın en büyük çamaşırhanesi!
Error, track not found: Sistemin işleyişi-Bir soygun mekanizması!
Error, track not found: Bahadır Özgür-Yoksulun matematiği ve milyarlar!
Error, track not found: Bahadır Özgür-Fon skandalı neden şimdi patladı?!
Error, track not found: Bahadır Özgür-Gazetecilik ve baskı altında gerçekler!
Error, track not found: Bahadır Özgür-Sistemin içindeki büyük çarklar!
Error, track not found: REKOR İSTEK ALAN-MUGO'NUN SATIR CİĞERİ!
Error, track not found: Martijn Doolaard-Last rafters!
Error, track not found: Martijn Doolaard-Golden morning!
Error, track not found: Martijn Doolaard-The first boards!
Error, track not found: Martijn Doolaard-Pancakes for lunch!
Error, track not found: Martijn Doolaard-Installing rafters!
Error, track not found: Martijn Doolaard-Sanding and staining!
Error, track not found: Martijn Doolaard-Cutting the rafters!
Error, track not found: Martijn Doolaard-Before sunrise!
Error, track not found: Martijn Doolaard-Movie!
Error, track not found: Martijn Doolaard-Chickens in the greenhouse!
Error, track not found: Martijn Doolaard-Cleaning the chicken coop & Autumn winds!
Error, track not found: Tram Miniature-Siku Trains collection. All siku trains!
Error, track not found: Martijn Doolaard-Prepairing the greenhouse!
Error, track not found: Martijn Doolaard-Talking about the rat problem!
Error, track not found: Martijn Doolaard-Making a rat trap!
Error, track not found: Intro-What Will You Do in a World Like This?!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Legolas ve Gimli!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Elfler ve Cüceler neden birbirini sevmez?!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Yüzük Kardeşliği Lothlorien'de!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Elrond'un Divanı!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Beş Ordular Muharebesi!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Erebor Macerası, Thranduil vs Thorin!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Beren ile Lúthien!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Silmaril ve Nauglamir!
Error, track not found: Elfler ve Cüceler Neden Düşman? (ELF CÜCE DÜŞMANLIĞI) | Yüzüklerin Efendisi-Ağaçsakal'ın Cücelere Bakışı!
Error, track not found: "Bu seçim iki çizgi arasında olacak"-Barolar Birliği başkanlığı düşüncesi var mı?!
Error, track not found: "Bu seçim iki çizgi arasında olacak"-Baro başkanlığını neden bırakmıştı, neden tekrar aday oldu?!
Error, track not found: "Bu seçim iki çizgi arasında olacak"-Ümit Kocasakal'ın akademik geçmişi!
Error, track not found: "Bu seçim iki çizgi arasında olacak"-Giriş!
Error, track not found: Martijn Doolaard-Washing the Land Rover!
Error, track not found: Martijn Doolaard-Testing Some Oils!
Error, track not found: Martijn Doolaard-Moment of Truth!
Error, track not found: Martijn Doolaard-Installing the Battery and Inverter!
Error, track not found: Martijn Doolaard-Making Battery Cables!
Error, track not found: Martijn Doolaard-Battery and Inverter Arrive!
Error, track not found: Martijn Doolaard-Tying Up the Grape Vines!
Error, track not found: Martijn Doolaard-Feeding the Cows!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Empanadalar serviste!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Andrea Şef'in mutfak yolculuğu!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Aras Şef'in tütsüleme hikâyesi!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Serhat ve mantar maceramızın hikâyesi!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Sofrada ilk lezzetler!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Polenta hazırlanıyor!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Füme somon hazırlıkları!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Mantarlı crostini!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Taze makarna hazırlığı!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Şefler menüyü anlatıyor!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Benim mantar arayışım!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Bi Pazarımız Var nasıl doğdu?!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Ormanda mantar avı başlıyor!
Error, track not found: İlker Ayrık’la Bi Pazarımız Var-Bi Pazarımız Var'a hoş geldiniz!!
Error, track not found: Porsche Kendini Sorguluyor!-MISSION S!
Error, track not found: Sultan + Shepard ft. Tishmal-Losing Ground!
Error, track not found: Uber Hesabım Geri Açıldı! + İşler Ne Durumda?-Amerika'da Motovlog!

In [4]:
df2= enrich_tracks("duzeniduzenadam",200,3)

In [5]:
df2.head()

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,Dünyanın en büyük çamaşırhanesi,Bahadır Özgür,,"26 Oct 2026, 10:19",1793009963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bir soygun mekanizması,Sistemin işleyişi,,"26 Oct 2026, 10:11",1793009482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yoksulun matematiği ve milyarlar,Bahadır Özgür,,"26 Oct 2026, 10:08",1793009287,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fon skandalı neden şimdi patladı?,Bahadır Özgür,,"26 Oct 2026, 10:06",1793009199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gazetecilik ve baskı altında gerçekler,Bahadır Özgür,,"26 Oct 2026, 10:04",1793009073,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df2.shape

(600, 12)

In [7]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         600 non-null    str
 1   artist       600 non-null    str
 2   album_       600 non-null    str
 3   date         600 non-null    str
 4   timestamp    600 non-null    str
 5   track_mbid   67 non-null     str
 6   duration     536 non-null    str
 7   listeners    536 non-null    str
 8   playcount    536 non-null    str
 9   artist_mbid  123 non-null    str
 10  album_info   87 non-null     str
 11  tags         536 non-null    object
dtypes: object(1), str(11)
memory usage: 56.4+ KB

In [8]:
df2.isna().sum()

name             0
artist           0
album_           0
date             0
timestamp        0
track_mbid     533
duration        64
listeners       64
playcount       64
artist_mbid    477
album_info     513
tags            64
dtype: int64

In [9]:
print("Unique artist count:",df2["artist"].nunique())
print("Unique track count: ", df2["name"].nunique())

Unique artist count: 214
Unique track count:  484

In [10]:
metadata= ["track_mbid","duration", "listeners", "playcount","artist_mbid","album_info","tags"]
is_nul= df2[metadata].isna()
all_null= is_nul.all(axis=1)
print(all_null.sum())

64

In [11]:
df2[all_null]

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,Dünyanın en büyük çamaşırhanesi,Bahadır Özgür,,"26 Oct 2026, 10:19",1793009963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bir soygun mekanizması,Sistemin işleyişi,,"26 Oct 2026, 10:11",1793009482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yoksulun matematiği ve milyarlar,Bahadır Özgür,,"26 Oct 2026, 10:08",1793009287,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fon skandalı neden şimdi patladı?,Bahadır Özgür,,"26 Oct 2026, 10:06",1793009199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gazetecilik ve baskı altında gerçekler,Bahadır Özgür,,"26 Oct 2026, 10:04",1793009073,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
224,Losing Ground,Sultan + Shepard ft. Tishmal,,"20 Oct 2026, 11:08",1792494502,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404,Losing Ground,Sultan + Shepard ft. Tishmal,,"14 Oct 2026, 10:21",1791973272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,Spectrum (Say My Name),Florence + the Machine,,"09 Oct 2026, 21:28",1791581319,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,Amerika'da Motovlog,Uber Hesabım Geri Açıldı! + İşler Ne Durumda?,,"09 Oct 2026, 12:14",1791548083,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,Spectrum (Say My Name),Florence + the Machine,,"07 Oct 2026, 19:30",1791401445,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df2.columns

Index(['name', 'artist', 'album_', 'date', 'timestamp', 'track_mbid',
       'duration', 'listeners', 'playcount', 'artist_mbid', 'album_info',
       'tags'],
      dtype='str')

In [13]:
df_temp = df2[["name","artist"]]

df_temp[df_temp.duplicated(keep=False)]

                                             name                  artist
13                            Something About You            Oscar & Deep
29                                Outro monologue        Martijn Doolaard
36                                   Coffee break        Martijn Doolaard
70                                Outro monologue        Martijn Doolaard
82                                       Chickens        Martijn Doolaard
..                                            ...                     ...
592                        Spectrum (Say My Name)  Florence + the Machine
593  Sweater Weather (Dave (LB) Afro House Remix)       The Neighbourhood
595                            The Rapture Pt.III       &ME, Black Coffee
597                              ALONE (extended)                  DannoW
599                      Fight for You (Devotion)      Marten Lou, Shouse

[188 rows x 2 columns]

In [14]:
print(df_temp.value_counts())

name                                                                    artist
ID                                                                      ID                           14
Lane 8 Fall 2020 Mixtape                                                This Never Happened           4
Making scaffolding platforms                                            Martijn Doolaard              4
Coffee break                                                            Martijn Doolaard              3
Innerbloom (CYRIL Remix)                                                RÜFÜS DU SOL                  3
                                                                                                     ..
Blessings (Daan de Haardt, Zeno Altea, Sanny Grooves Afro House Remix)  Calvin Harris, Clementine     1
I See The Sun                                                           Antdot, Maz, Dougwav          1
Nathanya House Live Set Summer at Icacos Island🌴☀️🇵🇷                    andreboros                    1
Wasting My Young Years (Billka Edit)                                    London Grammar                1
Who Loves the Sun (Original Mix)                                        Nu & Jo Ke                    1
Name: count, Length: 496, dtype: int64

In [15]:
df2[metadata].isna().sum()

track_mbid     533
duration        64
listeners       64
playcount       64
artist_mbid    477
album_info     513
tags            64
dtype: int64

In [16]:

mtd_maybe= df2[["duration","listeners","playcount","tags"]]
mtd_maybe.head()

  duration listeners playcount tags
0      NaN       NaN       NaN  NaN
1      NaN       NaN       NaN  NaN
2      NaN       NaN       NaN  NaN
3      NaN       NaN       NaN  NaN
4      NaN       NaN       NaN  NaN

In [17]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["duration"] != "0") &
        (mtd_maybe["duration"].notna())
    ]
))

82

In [18]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["listeners"] != "0") &
        (mtd_maybe["listeners"].notna())
    ]
))

536

In [19]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["playcount"] != "0") &
        (mtd_maybe["playcount"].notna())
    ]
))

536

In [20]:
print("NaN:", df["tags"].isna().sum())

print("[]:", df["tags"].apply(
    lambda x: isinstance(x, list) and len(x) == 0
).sum())

print("[...]:", df["tags"].apply(
    lambda x: isinstance(x, list) and len(x) > 0
).sum())

NaN: 64
[]: 534
[...]: 2

In [21]:
df2.head()

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,Dünyanın en büyük çamaşırhanesi,Bahadır Özgür,,"26 Oct 2026, 10:19",1793009963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bir soygun mekanizması,Sistemin işleyişi,,"26 Oct 2026, 10:11",1793009482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yoksulun matematiği ve milyarlar,Bahadır Özgür,,"26 Oct 2026, 10:08",1793009287,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fon skandalı neden şimdi patladı?,Bahadır Özgür,,"26 Oct 2026, 10:06",1793009199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gazetecilik ve baskı altında gerçekler,Bahadır Özgür,,"26 Oct 2026, 10:04",1793009073,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df2.loc[
    df2["tags"].apply(
        lambda x: isinstance(x, list) and len(x) > 0
    ),
    ["artist", "name", "tags"]
]

,artist,name,tags
341,Nirvana,Come as You Are,"[Grunge, rock, 90s, alternative, Nirvana]"
342,Red Hot Chili Peppers,Californication,"[rock, alternative rock, alternative, Red Hot ..."

In [23]:
meaning_mtd= df2[["playcount","listeners"]]
meaning_mtd.shape

(600, 2)

In [24]:
meaning_mtd.notna().sum()

playcount    536
listeners    536
dtype: int64

In [25]:
meaning_mtd.value_counts()

playcount  listeners
1          1            127
2          2             59
3          2             28
483399     21950         14
3          3             10
                       ...
185        53             1
49         27             1
87         42             1
587        263            1
20219      4968           1
Name: count, Length: 190, dtype: int64

In [26]:
df2[["name","artist","listeners","playcount"]].value_counts()

name                                                                    artist                     listeners  playcount
ID                                                                      ID                         21950      483399       14
Lane 8 Fall 2020 Mixtape                                                This Never Happened        269        836           4
Making scaffolding platforms                                            Martijn Doolaard           2          6             4
Coffee break                                                            Martijn Doolaard           12         16            3
Innerbloom (CYRIL Remix)                                                RÜFÜS DU SOL               16         28            3
                                                                                                                           ..
Blessings (Daan de Haardt, Zeno Altea, Sanny Grooves Afro House Remix)  Calvin Harris, Clementine  27         49            1
I See The Sun                                                           Antdot, Maz, Dougwav       42         87            1
Nathanya House Live Set Summer at Icacos Island🌴☀️🇵🇷                    andreboros                 1          1             1
Wasting My Young Years (Billka Edit)                                    London Grammar             263        587           1
Who Loves the Sun (Original Mix)                                        Nu & Jo Ke                 4968       20219         1
Name: count, Length: 434, dtype: int64

In [27]:
df2[df2["name"]=="Intro"]

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
28,Intro,Martijn Doolaard,,"25 Oct 2026, 17:53",1792950832,NaN,0,70,237,NaN,NaN,[]
134,Intro,The B1M,,"23 Oct 2026, 23:21",1792797714,NaN,0,1299,2946,NaN,NaN,[]
314,Intro,Whispers of Lisha,,"15 Oct 2026, 17:11",1792084278,NaN,0,1,1,NaN,NaN,[]
330,Intro,Fellowship Updates,,"15 Oct 2026, 08:03",1792051380,NaN,0,7,10,NaN,NaN,[]
445,Intro,Fellowship Updates,,"14 Oct 2026, 08:16",1791965811,NaN,0,7,10,NaN,NaN,[]
498,Intro,Business Insider,,"12 Oct 2026, 07:57",1791791851,NaN,0,720,1013,NaN,NaN,[]

In [28]:
from src.data_collection import search_videos

In [29]:
print(search_videos("Official Music Video",10))

      video_id                                        video_title  \
0  ko70cExuzZM  Taylor Swift - The Fate of Ophelia (Official M...
1  BH9IOx6xPgE  Valhalla Calling 🔥❄️ | Official Music Video | ...
2  yT_AfrHbAyA            Tyla - THAT GIRL (Official Music Video)
3  ekr2nIex040  ROSÉ &amp; Bruno Mars - APT. (Official Music ...
4  jZZ1cMD6r38  Vybz Kartel - Ever Blessed (Official Music Video)
5  U7aOZRgtdzw  PUNE PATTERN | MONYA DHIWAR | PROD BY : Micros...
6  SorF96ZGtiE  Darren Espanto - &#39;Paano Kung Tayo Na Lang&...
7  fLexgOxsZu0  Bruno Mars - The Lazy Song (Official Music Video)
8  I-5e_J3LWS8             Cardi B - AH HA [Official Music Video]
9  sckAitBFW-M    BRAT - Spit On His Grave (Official Music Video)

                                         description             channel  \
0  The official music video for “The Fate of Ophe...        Taylor Swift
1  VALHALLA CALLING — Official Music Video** ⚔️ “...      Ragal Ironbull
2  Tyla - THAT GIRL (Official Music Video) "A*POP...            TylaVEVO
3  ROSÉ & Bruno Mars - APT. Download/stream: http...                ROSÉ
4  Vybz Kartel - Ever Blessed (Official Music Vid...      VybzKartelVEVO
5  WELCOME TO PUNE PATTERN" COMPOSITION / WRITTER...        MONYA DHIWAR
6  Paano Kung Tayo Na Lang” Music Video of Darren...  ABS-CBN Star Music
7  The official music video for Bruno Mars' "The ...          Bruno Mars
8  Cardi B - AH HA Stream/Download: https://cardi...             Cardi B
9  The Official Music Video for BRAT “Spit On His...                BRAT

                 channel_id             published        published_time
0  UCqECaJ8Gagnn7YCbPEzWH6g  2025-10-05T23:00:06Z  2025-10-05T23:00:06Z
1  UCo50JWNAiW6CkMsWAZ9yyNQ  2026-09-16T16:00:06Z  2026-09-16T16:00:06Z
2  UCr2xjaS7CIx1OY7hYwrXb8A  2026-10-16T22:30:14Z  2026-10-16T22:30:14Z
3  UCBo1hnzxV9rz3WVsv__Rn1g  2024-10-18T04:00:07Z  2024-10-18T04:00:07Z
4  UCeRe0C1x1w8We6ghjVn4M5w  2026-10-23T16:00:03Z  2026-10-23T16:00:03Z
5  UCLYUYmRKy0tOQwC9ZvynL3Q  2026-10-25T04:30:06Z  2026-10-25T04:30:06Z
6  UCIWZ1_W5BqsvW9fm1cYFPpQ  2026-10-25T14:00:09Z  2026-10-25T14:00:09Z
7  UCoUM-UJ7rirJYP8CQ0EIaHA  2011-04-15T22:08:07Z  2011-04-15T22:08:07Z
8  UCxMAbVFmxKUVGAll0WVGpFw  2026-08-28T05:22:42Z  2026-08-28T05:22:42Z
9  UCUtbF-L_obVz3kw1b56IKNg  2026-10-26T04:00:10Z  2026-10-26T04:00:10Z

In [32]:
x=search_videos("Official Music Video", 5)
x

,video_id,video_title,description,channel,channel_id,published,published_time
0,ko70cExuzZM,Taylor Swift - The Fate of Ophelia (Official M...,The official music video for “The Fate of Ophe...,Taylor Swift,UCqECaJ8Gagnn7YCbPEzWH6g,2025-10-05T23:00:06Z,2025-10-05T23:00:06Z
1,BH9IOx6xPgE,Valhalla Calling 🔥❄️ | Official Music Video | ...,VALHALLA CALLING — Official Music Video** ⚔️ “...,Ragal Ironbull,UCo50JWNAiW6CkMsWAZ9yyNQ,2026-09-16T16:00:06Z,2026-09-16T16:00:06Z
2,yT_AfrHbAyA,Tyla - THAT GIRL (Official Music Video),"Tyla - THAT GIRL (Official Music Video) ""A*POP...",TylaVEVO,UCr2xjaS7CIx1OY7hYwrXb8A,2026-10-16T22:30:14Z,2026-10-16T22:30:14Z
3,ekr2nIex040,ROSÉ &amp; Bruno Mars - APT. (Official Music ...,ROSÉ & Bruno Mars - APT. Download/stream: http...,ROSÉ,UCBo1hnzxV9rz3WVsv__Rn1g,2024-10-18T04:00:07Z,2024-10-18T04:00:07Z
4,jZZ1cMD6r38,Vybz Kartel - Ever Blessed (Official Music Video),Vybz Kartel - Ever Blessed (Official Music Vid...,VybzKartelVEVO,UCeRe0C1x1w8We6ghjVn4M5w,2026-10-23T16:00:03Z,2026-10-23T16:00:03Z