In [1]:
import os
os.chdir("/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age")
os.getcwd()

'/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age'

In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from src.data_collection import get_all_recent_tracks
from src.data_collection import get_track_info 
from src.data_cleaning import clean_track_info
from src.data_cleaning import clean_tracks
from src.data_collection import enrich_tracks

### First View

In [3]:
df= enrich_tracks("duzeniduzenadam",200,3)

Error, track not found: Sultan + Shepard ft. Tishmal-Losing Ground!
Error, track not found: Clearing the Way to a Forgotten Watercress Bed + Zendure Solar Upgrade-Renovation in France #135!
Error, track not found: Clearing the Big Field + Cleaning Up Years of Dumped Junk-Renovation in South France #130!

In [4]:
df2= enrich_tracks("duzeniduzenadam",200,3)

In [5]:
df2.head()

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,Korolova - Argy - ARTBAT I Melodic Techno & Hy...,Anyma,,"05 Oct 2026, 12:30",1791203449,NaN,0,1,1,788307a8-ca6a-4775-b9a2-8d27d2af71ce,NaN,[]
1,Aurora Fade,Dub Deep Techno Mix 2026,,"05 Oct 2026, 09:29",1791192553,NaN,0,1,1,NaN,NaN,[]
2,Last Frontier,Dub Deep Techno Mix 2026,,"05 Oct 2026, 09:23",1791192199,NaN,0,1,1,NaN,NaN,[]
3,Hidden Valley Signal,Dub Deep Techno Mix 2026,,"05 Oct 2026, 09:18",1791191923,NaN,0,1,1,NaN,NaN,[]
4,Frozen Skyway,Dub Deep Techno Mix 2026,,"05 Oct 2026, 09:12",1791191577,NaN,0,1,1,NaN,NaN,[]

In [6]:
df2.shape

(600, 12)

In [7]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         600 non-null    str
 1   artist       600 non-null    str
 2   album_       600 non-null    str
 3   date         600 non-null    str
 4   timestamp    600 non-null    str
 5   track_mbid   66 non-null     str
 6   duration     596 non-null    str
 7   listeners    596 non-null    str
 8   playcount    596 non-null    str
 9   artist_mbid  98 non-null     str
 10  album_info   76 non-null     str
 11  tags         596 non-null    object
dtypes: object(1), str(11)
memory usage: 56.4+ KB

In [8]:
df2.isna().sum()

name             0
artist           0
album_           0
date             0
timestamp        0
track_mbid     534
duration         4
listeners        4
playcount        4
artist_mbid    502
album_info     524
tags             4
dtype: int64

In [9]:
print("Unique artist count:",df2["artist"].nunique())
print("Unique track count: ", df2["name"].nunique())

Unique artist count: 156
Unique track count:  492

In [10]:
metadata= ["track_mbid","duration", "listeners", "playcount","artist_mbid","album_info","tags"]
is_nul= df2[metadata].isna()
all_null= is_nul.all(axis=1)
print(all_null.sum())

4

In [11]:
df2[all_null]

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
505,Losing Ground,Sultan + Shepard ft. Tishmal,,"22 Sep 2026, 12:41",1790080874,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,Renovation in France #135,Clearing the Way to a Forgotten Watercress Bed...,,"21 Sep 2026, 22:46",1790030766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
524,Renovation in France #135,Clearing the Way to a Forgotten Watercress Bed...,,"21 Sep 2026, 22:15",1790028935,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,Renovation in South France #130,Clearing the Big Field + Cleaning Up Years of ...,,"21 Sep 2026, 19:10",1790017817,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df2.columns

Index(['name', 'artist', 'album_', 'date', 'timestamp', 'track_mbid',
       'duration', 'listeners', 'playcount', 'artist_mbid', 'album_info',
       'tags'],
      dtype='str')

In [13]:
df_temp = df2[["name","artist"]]

df_temp[df_temp.duplicated(keep=False)]

                                             name               artist
29                     Lane 8 Spring 2021 Mixtape  This Never Happened
39   Sweater Weather (Dave (LB) Afro House Remix)    The Neighbourhood
40                     The Man Who Sold the World              Nirvana
42                    Sky And Sand (Original Mix)     Paul Kalkbrenner
43   Sweater Weather (Dave (LB) Afro House Remix)    The Neighbourhood
..                                            ...                  ...
583                               Outro monologue     Martijn Doolaard
584                                Debarking logs     Martijn Doolaard
586                                Debarking logs     Martijn Doolaard
593                              Dinner and movie     Martijn Doolaard
598                               Outro monologue     Martijn Doolaard

[159 rows x 2 columns]

In [14]:
print(df_temp.value_counts())

name                  artist
Outro monologue       Martijn Doolaard    10
ID                    ID                   9
Intro                 Martijn Doolaard     5
Dinner                Martijn Doolaard     4
Dinner and movie      Martijn Doolaard     4
                                          ..
making a fire         Martijn Doolaard     1
Cutting fire wood     Martijn Doolaard     1
Chainsaw maintenance  Martijn Doolaard     1
Polishing boots       Martijn Doolaard     1
Adding gravel         Martijn Doolaard     1
Name: count, Length: 506, dtype: int64

In [15]:
df2[metadata].isna().sum()

track_mbid     534
duration         4
listeners        4
playcount        4
artist_mbid    502
album_info     524
tags             4
dtype: int64

In [16]:

mtd_maybe= df2[["duration","listeners","playcount","tags"]]
mtd_maybe.head()

  duration listeners playcount tags
0        0         1         1   []
1        0         1         1   []
2        0         1         1   []
3        0         1         1   []
4        0         1         1   []

In [17]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["duration"] != "0") &
        (mtd_maybe["duration"].notna())
    ]
))

74

In [18]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["listeners"] != "0") &
        (mtd_maybe["listeners"].notna())
    ]
))

596

In [19]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["playcount"] != "0") &
        (mtd_maybe["playcount"].notna())
    ]
))

596

In [20]:
print("NaN:", df["tags"].isna().sum())

print("[]:", df["tags"].apply(
    lambda x: isinstance(x, list) and len(x) == 0
).sum())

print("[...]:", df["tags"].apply(
    lambda x: isinstance(x, list) and len(x) > 0
).sum())

NaN: 4
[]: 575
[...]: 21

In [21]:
df2.head()

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,Korolova - Argy - ARTBAT I Melodic Techno & Hy...,Anyma,,"05 Oct 2026, 12:30",1791203449,NaN,0,1,1,788307a8-ca6a-4775-b9a2-8d27d2af71ce,NaN,[]
1,Aurora Fade,Dub Deep Techno Mix 2026,,"05 Oct 2026, 09:29",1791192553,NaN,0,1,1,NaN,NaN,[]
2,Last Frontier,Dub Deep Techno Mix 2026,,"05 Oct 2026, 09:23",1791192199,NaN,0,1,1,NaN,NaN,[]
3,Hidden Valley Signal,Dub Deep Techno Mix 2026,,"05 Oct 2026, 09:18",1791191923,NaN,0,1,1,NaN,NaN,[]
4,Frozen Skyway,Dub Deep Techno Mix 2026,,"05 Oct 2026, 09:12",1791191577,NaN,0,1,1,NaN,NaN,[]

In [22]:
df2.loc[
    df2["tags"].apply(
        lambda x: isinstance(x, list) and len(x) > 0
    ),
    ["artist", "name", "tags"]
]

,artist,name,tags
88,The Cranberries,Zombie,"[rock, alternative, 90s, alternative rock, fem..."
89,Rammstein,Du hast,"[industrial metal, metal, german, industrial, ..."
97,Red Hot Chili Peppers,Snow (Hey Oh),"[rock, alternative rock, alternative, funk, Re..."
98,Red Hot Chili Peppers,Dani California,"[rock, alternative rock, alternative, Red Hot ..."
99,Red Hot Chili Peppers,Under the Bridge,"[rock, alternative, alternative rock, 90s, Red..."
109,Red Hot Chili Peppers,Snow (Hey Oh),"[rock, alternative rock, alternative, funk, Re..."
135,Red Hot Chili Peppers,Can't Stop,"[rock, alternative rock, funk, alternative, Re..."
136,Red Hot Chili Peppers,Under the Bridge,"[rock, alternative, alternative rock, 90s, Red..."
137,Red Hot Chili Peppers,Dani California,"[rock, alternative rock, alternative, Red Hot ..."
138,Nirvana,Smells Like Teen Spirit,"[Grunge, rock, alternative, 90s, Nirvana]"
139,Red Hot Chili Peppers,Dark Necessities,"[2016, Funk Rock, rock, alternative rock, my t..."
141,Red Hot Chili Peppers,Snow (Hey Oh),"[rock, alternative rock, alternative, funk, Re..."
142,Red Hot Chili Peppers,Californication,"[rock, alternative rock, alternative, Red Hot ..."
374,Nirvana,About a Girl,"[Grunge, rock, alternative, alternative rock, ..."
375,Audioslave,Like a Stone,"[alternative rock, rock, Grunge, alternative, ..."
376,Nirvana,Smells Like Teen Spirit,"[Grunge, rock, alternative, 90s, Nirvana]"
377,Scorpions,Wind of Change,"[classic rock, rock, 80s, hard rock, scorpions]"
378,Lynyrd Skynyrd,Simple Man,"[classic rock, Southern Rock, 70s, rock, lynyr..."
384,Radiohead,Creep,"[alternative, alternative rock, rock, indie, r..."
385,Red Hot Chili Peppers,Californication,"[rock, alternative rock, alternative, Red Hot ..."
386,Nirvana,Come as You Are,"[Grunge, rock, 90s, alternative, Nirvana]"

In [23]:
meaning_mtd= df2[["playcount","listeners"]]
meaning_mtd.shape

(600, 2)

In [24]:
meaning_mtd.notna().sum()

playcount    596
listeners    596
dtype: int64

In [25]:
meaning_mtd.value_counts()

playcount  listeners
1          1            169
2          2             94
           1             68
3          2             23
4          3             21
                       ...
8          7              1
10         7              1
           4              1
17         16             1
54         21             1
Name: count, Length: 143, dtype: int64

In [26]:
df2[["name","artist","listeners","playcount"]].value_counts()

name                  artist            listeners  playcount
Outro monologue       Martijn Doolaard  58         282          10
ID                    ID                21914      482990        9
Intro                 Martijn Doolaard  70         237           5
Dinner                Martijn Doolaard  48         188           4
Dinner and movie      Martijn Doolaard  15         36            4
                                                                ..
making a fire         Martijn Doolaard  21         54            1
Cutting fire wood     Martijn Doolaard  3          5             1
Chainsaw maintenance  Martijn Doolaard  3          5             1
Polishing boots       Martijn Doolaard  5          6             1
Adding gravel         Martijn Doolaard  2          2             1
Name: count, Length: 503, dtype: int64

In [35]:
df2[df2["name"]=="Intro"]

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
121,Intro,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:26",1790756800,NaN,0,8,8,NaN,NaN,[]
163,Intro,Martijn Doolaard,,"29 Sep 2026, 17:23",1790702609,NaN,0,70,237,NaN,NaN,[]
201,Intro,Martijn Doolaard,,"28 Sep 2026, 15:44",1790610266,NaN,0,70,237,NaN,NaN,[]
219,Intro,Martijn Doolaard,,"28 Sep 2026, 15:07",1790608070,NaN,0,70,237,NaN,NaN,[]
257,Intro,Martijn Doolaard,,"28 Sep 2026, 13:46",1790603176,NaN,0,70,237,NaN,NaN,[]
462,Intro,The B1M,,"23 Sep 2026, 07:44",1790149462,NaN,0,1295,2922,NaN,NaN,[]
582,Intro,Martijn Doolaard,,"20 Sep 2026, 23:18",1789946301,NaN,0,70,237,NaN,NaN,[]