In [1]:
import os
os.chdir("/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age")
os.getcwd()

'/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age'

In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from src.data_collection import get_all_recent_tracks
from src.data_collection import get_track_info 
from src.data_cleaning import clean_track_info
from src.data_cleaning import clean_tracks
from src.data_collection import enrich_tracks

### First View

In [3]:
df= enrich_tracks("duzeniduzenadam",200,3)

{'artist': {'mbid': '', '#text': 'Fon mağduriyeti giderilebilir mi?'}, 'streamable': '0', 'image': [{'size': 'small', '#text': ''}, {'size': 'medium', '#text': ''}, {'size': 'large', '#text': ''}, {'size': 'extralarge', '#text': ''}], 'mbid': '', 'album': {'mbid': '', '#text': ''}, 'name': 'Bu işten kimler sorumludur?', '@attr': {'nowplaying': 'true'}, 'url': 'https://www.last.fm/music/Fon+ma%C4%9Fduriyeti+giderilebilir+mi%3F/_/Bu+i%C5%9Ften+kimler+sorumludur%3F'}
{'artist': {'mbid': '', '#text': 'Fon mağduriyeti giderilebilir mi?'}, 'streamable': '0', 'image': [{'size': 'small', '#text': ''}, {'size': 'medium', '#text': ''}, {'size': 'large', '#text': ''}, {'size': 'extralarge', '#text': ''}], 'mbid': '', 'album': {'mbid': '', '#text': ''}, 'name': 'Bu işten kimler sorumludur?', '@attr': {'nowplaying': 'true'}, 'url': 'https://www.last.fm/music/Fon+ma%C4%9Fduriyeti+giderilebilir+mi%3F/_/Bu+i%C5%9Ften+kimler+sorumludur%3F'}
{'artist': {'mbid': '', '#text': 'Fon mağduriyeti giderilebilir mi?'}, 'streamable': '0', 'image': [{'size': 'small', '#text': ''}, {'size': 'medium', '#text': ''}, {'size': 'large', '#text': ''}, {'size': 'extralarge', '#text': ''}], 'mbid': '', 'album': {'mbid': '', '#text': ''}, 'name': 'Bu işten kimler sorumludur?', '@attr': {'nowplaying': 'true'}, 'url': 'https://www.last.fm/music/Fon+ma%C4%9Fduriyeti+giderilebilir+mi%3F/_/Bu+i%C5%9Ften+kimler+sorumludur%3F'}
Error, track not found: Meaty&Cheesy-GÖRSELİ BAŞKA, TADI BAMBAŞKA! 10 ÜZERİNDEN 15 VERDİM!! (Mangalda Zebra Steak Tarifi)!
Error, track not found: KOKOREÇ DEĞİL, KRALLARIN TAVASI-ULTRA KOKOREÇ!
Error, track not found: Meaty&Cheesy-Doğru kesim tekniğiyle lezzet sırrı!
Error, track not found: Meaty&Cheesy-Mangalda eşit pişirme taktiği!
Error, track not found: Meaty&Cheesy-Etin yapısı ve pişirme zorluğu!
Error, track not found: Meaty&Cheesy-Dünya mutfağında bu etin adı ne?!
Error, track not found: Meaty&Cheesy-Keşfedilmemiş etin gizemi!
Error, track not found: Sultan + Shepard ft. Tishmal-Losing Ground!
Error, track not found: Clearing the Way to a Forgotten Watercress Bed + Zendure Solar Upgrade-Renovation in France #135!
Error, track not found: Clearing the Big Field + Cleaning Up Years of Dumped Junk-Renovation in South France #130!
Error, track not found: Martijn Doolaard-Fire + dinner!

In [4]:
df2= enrich_tracks("duzeniduzenadam",200,3)

In [5]:
df2.head()

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,BDDK Başkanı değişmeli mi?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:46",1790937993,NaN,0,1,1,NaN,NaN,[]
1,Bu işten kimler sorumludur?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:44",1790937864,NaN,0,1,1,NaN,NaN,[]
2,MSCI endeksi nedir?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:41",1790937710,NaN,0,1,1,NaN,NaN,[]
3,Bankacılık sisteminde risk oluşturur mu?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:41",1790937671,NaN,0,1,1,NaN,NaN,[]
4,Bankaların sayısı artar mı?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:40",1790937623,NaN,0,1,1,NaN,NaN,[]

In [6]:
df2.shape

(600, 12)

In [7]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         600 non-null    str
 1   artist       600 non-null    str
 2   album_       600 non-null    str
 3   date         600 non-null    str
 4   timestamp    600 non-null    str
 5   track_mbid   65 non-null     str
 6   duration     588 non-null    str
 7   listeners    588 non-null    str
 8   playcount    588 non-null    str
 9   artist_mbid  93 non-null     str
 10  album_info   70 non-null     str
 11  tags         588 non-null    object
dtypes: object(1), str(11)
memory usage: 56.4+ KB

In [8]:
df2.isna().sum()

name             0
artist           0
album_           0
date             0
timestamp        0
track_mbid     535
duration        12
listeners       12
playcount       12
artist_mbid    507
album_info     530
tags            12
dtype: int64

In [9]:
print("Unique artist count:",df2["artist"].nunique())
print("Unique track count: ", df2["name"].nunique())

Unique artist count: 143
Unique track count:  492

In [10]:
metadata= ["track_mbid","duration", "listeners", "playcount","artist_mbid","album_info","tags"]
is_nul= df2[metadata].isna()
all_null= is_nul.all(axis=1)
print(all_null.sum())

12

In [11]:
df2[all_null]

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
15,"GÖRSELİ BAŞKA, TADI BAMBAŞKA! 10 ÜZERİNDEN 15 ...",Meaty&Cheesy,,"01 Oct 2026, 15:07",1790867274,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,ULTRA KOKOREÇ,"KOKOREÇ DEĞİL, KRALLARIN TAVASI",,"01 Oct 2026, 14:40",1790865607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Doğru kesim tekniğiyle lezzet sırrı,Meaty&Cheesy,,"01 Oct 2026, 14:37",1790865451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Mangalda eşit pişirme taktiği,Meaty&Cheesy,,"01 Oct 2026, 14:36",1790865376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Etin yapısı ve pişirme zorluğu,Meaty&Cheesy,,"01 Oct 2026, 14:35",1790865335,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Dünya mutfağında bu etin adı ne?,Meaty&Cheesy,,"01 Oct 2026, 14:34",1790865289,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Keşfedilmemiş etin gizemi,Meaty&Cheesy,,"01 Oct 2026, 14:34",1790865240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,Losing Ground,Sultan + Shepard ft. Tishmal,,"22 Sep 2026, 12:41",1790080874,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458,Renovation in France #135,Clearing the Way to a Forgotten Watercress Bed...,,"21 Sep 2026, 22:46",1790030766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,Renovation in France #135,Clearing the Way to a Forgotten Watercress Bed...,,"21 Sep 2026, 22:15",1790028935,NaN,NaN,NaN,NaN,NaN,NaN,NaN
464,Renovation in South France #130,Clearing the Big Field + Cleaning Up Years of ...,,"21 Sep 2026, 19:10",1790017817,NaN,NaN,NaN,NaN,NaN,NaN,NaN
555,Fire + dinner,Martijn Doolaard,,"20 Sep 2026, 21:57",1789941472,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df2.columns

Index(['name', 'artist', 'album_', 'date', 'timestamp', 'track_mbid',
       'duration', 'listeners', 'playcount', 'artist_mbid', 'album_info',
       'tags'],
      dtype='str')

In [13]:
df_temp = df2[["name","artist"]]

df_temp[df_temp.duplicated(keep=False)]

,name,artist
0,BDDK Başkanı değişmeli mi?,Fon mağduriyeti giderilebilir mi?
1,Bu işten kimler sorumludur?,Fon mağduriyeti giderilebilir mi?
2,MSCI endeksi nedir?,Fon mağduriyeti giderilebilir mi?
3,Bankacılık sisteminde risk oluşturur mu?,Fon mağduriyeti giderilebilir mi?
4,Bankaların sayısı artar mı?,Fon mağduriyeti giderilebilir mi?
...,...,...
595,Digging,Martijn Doolaard
596,Intro,Martijn Doolaard
597,Outro monologue,#227 The Roof Construction Begins
598,Checking the garden beds,#227 The Roof Construction Begins
599,Misty Mountain hike,#227 The Roof Construction Begins

In [14]:
print(df_temp.value_counts())

name                  artist
Outro monologue       Martijn Doolaard    12
ID                    ID                   9
Intro                 Martijn Doolaard     7
Dinner                Martijn Doolaard     6
Dinner and movie      Martijn Doolaard     5
                                          ..
Collecting rocks      Martijn Doolaard     1
Dinner and film       Martijn Doolaard     1
Eating chestnuts      Martijn Doolaard     1
Cooking chestnuts     Martijn Doolaard     1
Collecting chestnuts  Martijn Doolaard     1
Name: count, Length: 504, dtype: int64

In [33]:
df2[metadata].isna().sum()

track_mbid     535
duration        12
listeners       12
playcount       12
artist_mbid    507
album_info     530
tags            12
dtype: int64

In [ ]:

mtd_maybe= df2[["duration","listeners","playcount","tags"]]
mtd_maybe.head()

  duration listeners playcount tags
0        0         1         1   []
1        0         1         1   []
2        0         1         1   []
3        0         1         1   []
4        0         1         1   []

In [32]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["duration"] != "0") &
        (mtd_maybe["duration"].notna())
    ]
))

69

In [34]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["listeners"] != "0") &
        (mtd_maybe["listeners"].notna())
    ]
))

588

In [35]:
print(len(
    mtd_maybe.loc[
        (mtd_maybe["playcount"] != "0") &
        (mtd_maybe["playcount"].notna())
    ]
))

588

In [44]:
print("NaN:", df["tags"].isna().sum())

print("[]:", df["tags"].apply(
    lambda x: isinstance(x, list) and len(x) == 0
).sum())

print("[...]:", df["tags"].apply(
    lambda x: isinstance(x, list) and len(x) > 0
).sum())

NaN: 12
[]: 567
[...]: 21

In [47]:
df2.head()

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,BDDK Başkanı değişmeli mi?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:46",1790937993,NaN,0,1,1,NaN,NaN,[]
1,Bu işten kimler sorumludur?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:44",1790937864,NaN,0,1,1,NaN,NaN,[]
2,MSCI endeksi nedir?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:41",1790937710,NaN,0,1,1,NaN,NaN,[]
3,Bankacılık sisteminde risk oluşturur mu?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:41",1790937671,NaN,0,1,1,NaN,NaN,[]
4,Bankaların sayısı artar mı?,Fon mağduriyeti giderilebilir mi?,,"02 Oct 2026, 10:40",1790937623,NaN,0,1,1,NaN,NaN,[]

In [48]:
df2.loc[
    df2["tags"].apply(
        lambda x: isinstance(x, list) and len(x) > 0
    ),
    ["artist", "name", "tags"]
]

,artist,name,tags
23,The Cranberries,Zombie,"[rock, alternative, 90s, alternative rock, fem..."
24,Rammstein,Du hast,"[industrial metal, metal, german, industrial, ..."
32,Red Hot Chili Peppers,Snow (Hey Oh),"[rock, alternative rock, alternative, funk, Re..."
33,Red Hot Chili Peppers,Dani California,"[rock, alternative rock, alternative, Red Hot ..."
34,Red Hot Chili Peppers,Under the Bridge,"[rock, alternative, alternative rock, 90s, Red..."
44,Red Hot Chili Peppers,Snow (Hey Oh),"[rock, alternative rock, alternative, funk, Re..."
70,Red Hot Chili Peppers,Can't Stop,"[rock, alternative rock, funk, alternative, Re..."
71,Red Hot Chili Peppers,Under the Bridge,"[rock, alternative, alternative rock, 90s, Red..."
72,Red Hot Chili Peppers,Dani California,"[rock, alternative rock, alternative, Red Hot ..."
73,Nirvana,Smells Like Teen Spirit,"[Grunge, rock, alternative, 90s, Nirvana]"
74,Red Hot Chili Peppers,Dark Necessities,"[2016, Funk Rock, rock, alternative rock, my t..."
76,Red Hot Chili Peppers,Snow (Hey Oh),"[rock, alternative rock, alternative, funk, Re..."
77,Red Hot Chili Peppers,Californication,"[rock, alternative rock, alternative, Red Hot ..."
309,Nirvana,About a Girl,"[Grunge, rock, alternative, alternative rock, ..."
310,Audioslave,Like a Stone,"[alternative rock, rock, Grunge, alternative, ..."
311,Nirvana,Smells Like Teen Spirit,"[Grunge, rock, alternative, 90s, Nirvana]"
312,Scorpions,Wind of Change,"[classic rock, rock, 80s, hard rock, scorpions]"
313,Lynyrd Skynyrd,Simple Man,"[classic rock, Southern Rock, 70s, rock, lynyr..."
319,Radiohead,Creep,"[alternative, alternative rock, rock, indie, r..."
320,Red Hot Chili Peppers,Californication,"[rock, alternative rock, alternative, Red Hot ..."
321,Nirvana,Come as You Are,"[Grunge, rock, 90s, alternative, Nirvana]"

In [49]:
meaning_mtd= df2[["playcount","listeners"]]
meaning_mtd.shape

(600, 2)

In [51]:
meaning_mtd.notna().sum()

playcount    588
listeners    588
dtype: int64

In [60]:
meaning_mtd.value_counts()

playcount  listeners
1          1            205
2          2             82
3          2             33
4          3             22
2          1             17
                       ...
17         16             1
11         9              1
14         9              1
57         34             1
29         17             1
Name: count, Length: 140, dtype: int64

In [62]:
df2[["name","artist","listeners","playcount"]].value_counts()

name                  artist            listeners  playcount
Outro monologue       Martijn Doolaard  58         282          12
ID                    ID                21910      482935        9
Intro                 Martijn Doolaard  70         237           7
Dinner                Martijn Doolaard  48         188           6
Dinner and movie      Martijn Doolaard  15         36            5
                                                                ..
Collecting rocks      Martijn Doolaard  2          3             1
Dinner and film       Martijn Doolaard  2          3             1
Eating chestnuts      Martijn Doolaard  2          3             1
Cooking chestnuts     Martijn Doolaard  3          4             1
Collecting chestnuts  Martijn Doolaard  2          3             1
Name: count, Length: 493, dtype: int64