In [1]:
import os
os.chdir("/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age")
os.getcwd()

'/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age'

In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from src.data_collection import get_all_recent_tracks
from src.data_collection import get_track_info 
from src.data_cleaning import clean_track_info
from src.data_cleaning import clean_tracks
from src.data_collection import enrich_tracks

In [3]:
username = input("Enter your last.fm username: ")

data = get_all_recent_tracks(username,10,3)
cleaned_data= clean_tracks(data)
print(len(cleaned_data))

Status code: 200
totalPages = 25970
Status code: 200
Status code: 200
30

In [4]:
df= pd.DataFrame(cleaned_data)
df.head()

,name,artist,album,date,timestamp
0,Sukuru,DannoW,Sukuru,"30 Sep 2026, 15:15",1790781308
1,ALONE (extended),DannoW,,"30 Sep 2026, 15:07",1790780855
2,Fight for You (Devotion),"Marten Lou, Shouse",,"30 Sep 2026, 15:01",1790780517
3,Late Night,Foals,Holy Fire,"30 Sep 2026, 14:53",1790780008
4,Sky And Sand (Original Mix),Paul Kalkbrenner,Sky and Sand,"30 Sep 2026, 14:44",1790779471

In [5]:
df.shape

(30, 5)

In [6]:
df.columns

Index(['name', 'artist', 'album', 'date', 'timestamp'], dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       30 non-null     str
 1   artist     30 non-null     str
 2   album      30 non-null     str
 3   date       30 non-null     str
 4   timestamp  30 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

In [8]:
df.dtypes

name         str
artist       str
album        str
date         str
timestamp    str
dtype: object

In [9]:
df.isna().sum()

name         0
artist       0
album        0
date         0
timestamp    0
dtype: int64

In [10]:
df.nunique()

name         26
artist       12
album         7
date         30
timestamp    30
dtype: int64

In [11]:
df["timestamp"].sort_values(ascending=False)

0     1790781308
1     1790780855
2     1790780517
3     1790780008
4     1790779471
5     1790779117
6     1790778824
7     1790778551
8     1790768932
9     1790765080
10    1790764536
11    1790764117
12    1790763878
13    1790763683
14    1790763381
15    1790763344
16    1790762654
17    1790761954
18    1790759945
19    1790759472
20    1790758121
21    1790757664
22    1790757544
23    1790757342
24    1790757210
25    1790757094
26    1790757030
27    1790756966
28    1790756884
29    1790756800
Name: timestamp, dtype: str

In [12]:
df["timestamp"].sort_values(ascending=True)

29    1790756800
28    1790756884
27    1790756966
26    1790757030
25    1790757094
24    1790757210
23    1790757342
22    1790757544
21    1790757664
20    1790758121
19    1790759472
18    1790759945
17    1790761954
16    1790762654
15    1790763344
14    1790763381
13    1790763683
12    1790763878
11    1790764117
10    1790764536
9     1790765080
8     1790768932
7     1790778551
6     1790778824
5     1790779117
4     1790779471
3     1790780008
2     1790780517
1     1790780855
0     1790781308
Name: timestamp, dtype: str

In [13]:
df["artist"].value_counts()

artist
Timur Soykan anlattı                    6
Why Real Feta Cheese Is Disappearing    6
Red Hot Chili Peppers                   5
Veritasium                              3
DannoW                                  2
Kirsten Dirksen                         2
Marten Lou, Shouse                      1
Foals                                   1
Paul Kalkbrenner                        1
Korolova                                1
Aynada Gören Korkuyordu!                1
Giolì & Assia                           1
Name: count, dtype: int64

In [14]:
df["name"].value_counts()

name
Snow (Hey Oh)                                                                  2
Bu Dolandırıcılık Neden Engellenmiyor?                                         2
Yeni Türkiye'nin Karanlık Ekonomi Özeti                                        2
He dreamed of self-feeding solar house. So he built A-frame greenhouse home    2
Sukuru                                                                         1
ALONE (extended)                                                               1
Fight for You (Devotion)                                                       1
Late Night                                                                     1
Sky And Sand (Original Mix)                                                    1
Dani California                                                                1
Under the Bridge                                                               1
The Adventures of Rain Dance Maggie                                            1
Captive Soul 100  @ Sagrada Familia, Barcelona                                 1
Altın Çocuklar ve Kayıp Milyarlar                                              1
Borsa İstanbul'da 900 Milyarlık Vurgun                                         1
Volvo 850R Nasıl Her Şeyi Değiştirdi?                                          1
#DiesisLive @Fjallsarlon Glacier Lagoon, Iceland                               1
The Inside of a Jet Engine                                                     1
Why are jet engines so big?                                                    1
How a jet engine works                                                         1
Impact of outbreak                                                             1
Struggling restaurants                                                         1
Farmer protests                                                                1
Debate over vaccination                                                        1
How feta is made                                                               1
Intro                                                                          1
Name: count, dtype: int64

In [15]:
df["album"].value_counts()

album
                         23
Stadium Arcadium          2
Sukuru                    1
Holy Fire                 1
Sky and Sand              1
Blood Sugar Sex Magik     1
I'm With You              1
Name: count, dtype: int64

In [16]:
df

,name,artist,album,date,timestamp
0,Sukuru,DannoW,Sukuru,"30 Sep 2026, 15:15",1790781308
1,ALONE (extended),DannoW,,"30 Sep 2026, 15:07",1790780855
2,Fight for You (Devotion),"Marten Lou, Shouse",,"30 Sep 2026, 15:01",1790780517
3,Late Night,Foals,Holy Fire,"30 Sep 2026, 14:53",1790780008
4,Sky And Sand (Original Mix),Paul Kalkbrenner,Sky and Sand,"30 Sep 2026, 14:44",1790779471
5,Snow (Hey Oh),Red Hot Chili Peppers,Stadium Arcadium,"30 Sep 2026, 14:38",1790779117
6,Dani California,Red Hot Chili Peppers,Stadium Arcadium,"30 Sep 2026, 14:33",1790778824
7,Under the Bridge,Red Hot Chili Peppers,Blood Sugar Sex Magik,"30 Sep 2026, 14:29",1790778551
8,The Adventures of Rain Dance Maggie,Red Hot Chili Peppers,I'm With You,"30 Sep 2026, 11:48",1790768932
9,"Captive Soul 100 @ Sagrada Familia, Barcelona",Korolova,,"30 Sep 2026, 10:44",1790765080
10,Altın Çocuklar ve Kayıp Milyarlar,Timur Soykan anlattı,,"30 Sep 2026, 10:35",1790764536
11,Bu Dolandırıcılık Neden Engellenmiyor?,Timur Soykan anlattı,,"30 Sep 2026, 10:28",1790764117
12,Yeni Türkiye'nin Karanlık Ekonomi Özeti,Timur Soykan anlattı,,"30 Sep 2026, 10:24",1790763878
13,Bu Dolandırıcılık Neden Engellenmiyor?,Timur Soykan anlattı,,"30 Sep 2026, 10:21",1790763683
14,Yeni Türkiye'nin Karanlık Ekonomi Özeti,Timur Soykan anlattı,,"30 Sep 2026, 10:16",1790763381
15,Borsa İstanbul'da 900 Milyarlık Vurgun,Timur Soykan anlattı,,"30 Sep 2026, 10:15",1790763344
16,Volvo 850R Nasıl Her Şeyi Değiştirdi?,Aynada Gören Korkuyordu!,,"30 Sep 2026, 10:04",1790762654
17,Snow (Hey Oh),Red Hot Chili Peppers,,"30 Sep 2026, 09:52",1790761954
18,"#DiesisLive @Fjallsarlon Glacier Lagoon, Iceland",Giolì & Assia,,"30 Sep 2026, 09:19",1790759945
19,He dreamed of self-feeding solar house. So he ...,Kirsten Dirksen,,"30 Sep 2026, 09:11",1790759472
20,He dreamed of self-feeding solar house. So he ...,Kirsten Dirksen,,"30 Sep 2026, 08:48",1790758121
21,The Inside of a Jet Engine,Veritasium,,"30 Sep 2026, 08:41",1790757664
22,Why are jet engines so big?,Veritasium,,"30 Sep 2026, 08:39",1790757544
23,How a jet engine works,Veritasium,,"30 Sep 2026, 08:35",1790757342
24,Impact of outbreak,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:33",1790757210
25,Struggling restaurants,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:31",1790757094
26,Farmer protests,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:30",1790757030
27,Debate over vaccination,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:29",1790756966
28,How feta is made,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:28",1790756884
29,Intro,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:26",1790756800

In [17]:
from data_collection import get_track_info
from data_cleaning import clean_track_info

In [18]:
df.head()

,name,artist,album,date,timestamp
0,Sukuru,DannoW,Sukuru,"30 Sep 2026, 15:15",1790781308
1,ALONE (extended),DannoW,,"30 Sep 2026, 15:07",1790780855
2,Fight for You (Devotion),"Marten Lou, Shouse",,"30 Sep 2026, 15:01",1790780517
3,Late Night,Foals,Holy Fire,"30 Sep 2026, 14:53",1790780008
4,Sky And Sand (Original Mix),Paul Kalkbrenner,Sky and Sand,"30 Sep 2026, 14:44",1790779471

In [19]:
af= get_track_info("Late Night","Foals")

af

Status code: 200

{'track': {'name': 'Foals',
  'url': 'https://www.last.fm/music/Late+Night+Alumni/_/Foals',
  'duration': '0',
  'streamable': {'#text': '0', 'fulltrack': '0'},
  'listeners': '2',
  'playcount': '2',
  'artist': {'name': 'Late Night Alumni',
   'mbid': 'c0766f2c-6197-4852-9f47-9dfd71923afa',
   'url': 'https://www.last.fm/music/Late+Night+Alumni'},
  'toptags': {'tag': []}}}

In [20]:
af= clean_track_info(af)
af= pd.DataFrame(af)
af.head()

Empty DataFrame
Columns: [name, track_mbid, duration, listeners, playcount, artist_mbid, artist, album, tags]
Index: []

In [21]:
len(df.drop_duplicates(["artist","name"]))

26

In [22]:
df.drop_duplicates(["artist","name"])

,name,artist,album,date,timestamp
0,Sukuru,DannoW,Sukuru,"30 Sep 2026, 15:15",1790781308
1,ALONE (extended),DannoW,,"30 Sep 2026, 15:07",1790780855
2,Fight for You (Devotion),"Marten Lou, Shouse",,"30 Sep 2026, 15:01",1790780517
3,Late Night,Foals,Holy Fire,"30 Sep 2026, 14:53",1790780008
4,Sky And Sand (Original Mix),Paul Kalkbrenner,Sky and Sand,"30 Sep 2026, 14:44",1790779471
5,Snow (Hey Oh),Red Hot Chili Peppers,Stadium Arcadium,"30 Sep 2026, 14:38",1790779117
6,Dani California,Red Hot Chili Peppers,Stadium Arcadium,"30 Sep 2026, 14:33",1790778824
7,Under the Bridge,Red Hot Chili Peppers,Blood Sugar Sex Magik,"30 Sep 2026, 14:29",1790778551
8,The Adventures of Rain Dance Maggie,Red Hot Chili Peppers,I'm With You,"30 Sep 2026, 11:48",1790768932
9,"Captive Soul 100 @ Sagrada Familia, Barcelona",Korolova,,"30 Sep 2026, 10:44",1790765080
10,Altın Çocuklar ve Kayıp Milyarlar,Timur Soykan anlattı,,"30 Sep 2026, 10:35",1790764536
11,Bu Dolandırıcılık Neden Engellenmiyor?,Timur Soykan anlattı,,"30 Sep 2026, 10:28",1790764117
12,Yeni Türkiye'nin Karanlık Ekonomi Özeti,Timur Soykan anlattı,,"30 Sep 2026, 10:24",1790763878
15,Borsa İstanbul'da 900 Milyarlık Vurgun,Timur Soykan anlattı,,"30 Sep 2026, 10:15",1790763344
16,Volvo 850R Nasıl Her Şeyi Değiştirdi?,Aynada Gören Korkuyordu!,,"30 Sep 2026, 10:04",1790762654
18,"#DiesisLive @Fjallsarlon Glacier Lagoon, Iceland",Giolì & Assia,,"30 Sep 2026, 09:19",1790759945
19,He dreamed of self-feeding solar house. So he ...,Kirsten Dirksen,,"30 Sep 2026, 09:11",1790759472
21,The Inside of a Jet Engine,Veritasium,,"30 Sep 2026, 08:41",1790757664
22,Why are jet engines so big?,Veritasium,,"30 Sep 2026, 08:39",1790757544
23,How a jet engine works,Veritasium,,"30 Sep 2026, 08:35",1790757342
24,Impact of outbreak,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:33",1790757210
25,Struggling restaurants,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:31",1790757094
26,Farmer protests,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:30",1790757030
27,Debate over vaccination,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:29",1790756966
28,How feta is made,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:28",1790756884
29,Intro,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:26",1790756800

In [23]:
ap= enrich_tracks("duzeniduzenadam",10,3)

Status code: 200
totalPages = 25970
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Error, track not found: Aynada Gören Korkuyordu!-Volvo 850R Nasıl Her Şeyi Değiştirdi?!
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200
Status code: 200

In [25]:
ap.head()

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,Sukuru,DannoW,Sukuru,"30 Sep 2026, 15:15",1790781308,NaN,442000,98,256,NaN,Sukuru,[]
1,ALONE (extended),DannoW,,"30 Sep 2026, 15:07",1790780855,NaN,0,61,142,NaN,NaN,[]
2,Fight for You (Devotion),"Marten Lou, Shouse",,"30 Sep 2026, 15:01",1790780517,NaN,0,64,164,NaN,NaN,[]
3,Late Night,Foals,Holy Fire,"30 Sep 2026, 14:53",1790780008,03fe9042-a28c-4077-ac76-35b6324065bc,327000,289614,2188794,6a65d878-fcd0-42cf-aff9-ca1d636a8bcc,Holy Fire,[]
4,Sky And Sand (Original Mix),Paul Kalkbrenner,Sky and Sand,"30 Sep 2026, 14:44",1790779471,NaN,230000,4691,43780,a5f92d47-b562-4582-b267-71963a515f4c,Sky and Sand,[]

In [28]:
print(ap.shape)
print(ap.isna().sum())

(30, 12)
name            0
artist          0
album_          0
date            0
timestamp       0
track_mbid     24
duration        1
listeners       1
playcount       1
artist_mbid    18
album_info     22
tags            1
dtype: int64