In [1]:
import os
os.chdir("/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age")
os.getcwd()

'/home/hashalike/Belgeler/Yazılım/Projeler/Music Taste & Age'

In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from src.data_collection import get_all_recent_tracks
from src.data_collection import get_track_info 
from src.data_cleaning import clean_track_info
from src.data_cleaning import clean_tracks
from src.data_collection import enrich_tracks

### First View

In [3]:
df= enrich_tracks("duzeniduzenadam",200,3)

Error, track not found: Meaty&Cheesy-GÖRSELİ BAŞKA, TADI BAMBAŞKA! 10 ÜZERİNDEN 15 VERDİM!! (Mangalda Zebra Steak Tarifi)!
Error, track not found: KOKOREÇ DEĞİL, KRALLARIN TAVASI-ULTRA KOKOREÇ!
Error, track not found: Meaty&Cheesy-Doğru kesim tekniğiyle lezzet sırrı!
Error, track not found: Meaty&Cheesy-Mangalda eşit pişirme taktiği!
Error, track not found: Meaty&Cheesy-Etin yapısı ve pişirme zorluğu!
Error, track not found: Meaty&Cheesy-Dünya mutfağında bu etin adı ne?!
Error, track not found: Meaty&Cheesy-Keşfedilmemiş etin gizemi!
Error, track not found: Aynada Gören Korkuyordu!-Volvo 850R Nasıl Her Şeyi Değiştirdi?!
Error, track not found: Onur Benli-Arrival at Çeşme!
Error, track not found: Sultan + Shepard ft. Tishmal-Losing Ground!
Error, track not found: Clearing the Way to a Forgotten Watercress Bed + Zendure Solar Upgrade-Renovation in France #135!
Error, track not found: Clearing the Big Field + Cleaning Up Years of Dumped Junk-Renovation in South France #130!
Error, track not found: Martijn Doolaard-Fire + dinner!

In [4]:
df2= enrich_tracks("duzeniduzenadam",200,3)

In [5]:
df2.head()

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,"GÖRSELİ BAŞKA, TADI BAMBAŞKA! 10 ÜZERİNDEN 15 ...",Meaty&Cheesy,,"01 Oct 2026, 15:07",1790867274,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ULTRA KOKOREÇ,"KOKOREÇ DEĞİL, KRALLARIN TAVASI",,"01 Oct 2026, 14:40",1790865607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Doğru kesim tekniğiyle lezzet sırrı,Meaty&Cheesy,,"01 Oct 2026, 14:37",1790865451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mangalda eşit pişirme taktiği,Meaty&Cheesy,,"01 Oct 2026, 14:36",1790865376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Etin yapısı ve pişirme zorluğu,Meaty&Cheesy,,"01 Oct 2026, 14:35",1790865335,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df2.shape

(600, 12)

In [7]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         600 non-null    str
 1   artist       600 non-null    str
 2   album_       600 non-null    str
 3   date         600 non-null    str
 4   timestamp    600 non-null    str
 5   track_mbid   65 non-null     str
 6   duration     586 non-null    str
 7   listeners    586 non-null    str
 8   playcount    586 non-null    str
 9   artist_mbid  95 non-null     str
 10  album_info   70 non-null     str
 11  tags         586 non-null    object
dtypes: object(1), str(11)
memory usage: 56.4+ KB

In [8]:
df2.isna().sum()

name             0
artist           0
album_           0
date             0
timestamp        0
track_mbid     535
duration        14
listeners       14
playcount       14
artist_mbid    505
album_info     530
tags            14
dtype: int64

In [9]:
print("Unique artist count:",df2["artist"].nunique())
print("Unique track count: ", df2["name"].nunique())

Unique artist count: 145
Unique track count:  494

In [10]:
metadata= ["track_mbid","duration", "listeners", "playcount","artist_mbid","album_info","tags"]
is_nul= df2[metadata].isna()
all_null= is_nul.all(axis=1)
print(all_null.sum())

14

In [11]:
df2[all_null]

,name,artist,album_,date,timestamp,track_mbid,duration,listeners,playcount,artist_mbid,album_info,tags
0,"GÖRSELİ BAŞKA, TADI BAMBAŞKA! 10 ÜZERİNDEN 15 ...",Meaty&Cheesy,,"01 Oct 2026, 15:07",1790867274,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ULTRA KOKOREÇ,"KOKOREÇ DEĞİL, KRALLARIN TAVASI",,"01 Oct 2026, 14:40",1790865607,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Doğru kesim tekniğiyle lezzet sırrı,Meaty&Cheesy,,"01 Oct 2026, 14:37",1790865451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mangalda eşit pişirme taktiği,Meaty&Cheesy,,"01 Oct 2026, 14:36",1790865376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Etin yapısı ve pişirme zorluğu,Meaty&Cheesy,,"01 Oct 2026, 14:35",1790865335,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Dünya mutfağında bu etin adı ne?,Meaty&Cheesy,,"01 Oct 2026, 14:34",1790865289,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Keşfedilmemiş etin gizemi,Meaty&Cheesy,,"01 Oct 2026, 14:34",1790865240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Volvo 850R Nasıl Her Şeyi Değiştirdi?,Aynada Gören Korkuyordu!,,"30 Sep 2026, 10:04",1790762654,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Arrival at Çeşme,Onur Benli,,"30 Sep 2026, 08:08",1790755703,NaN,NaN,NaN,NaN,NaN,NaN,NaN
425,Losing Ground,Sultan + Shepard ft. Tishmal,,"22 Sep 2026, 12:41",1790080874,NaN,NaN,NaN,NaN,NaN,NaN,NaN
443,Renovation in France #135,Clearing the Way to a Forgotten Watercress Bed...,,"21 Sep 2026, 22:46",1790030766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
444,Renovation in France #135,Clearing the Way to a Forgotten Watercress Bed...,,"21 Sep 2026, 22:15",1790028935,NaN,NaN,NaN,NaN,NaN,NaN,NaN
449,Renovation in South France #130,Clearing the Big Field + Cleaning Up Years of ...,,"21 Sep 2026, 19:10",1790017817,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,Fire + dinner,Martijn Doolaard,,"20 Sep 2026, 21:57",1789941472,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df2.columns

Index(['name', 'artist', 'album_', 'date', 'timestamp', 'track_mbid',
       'duration', 'listeners', 'playcount', 'artist_mbid', 'album_info',
       'tags'],
      dtype='str')

In [13]:
df_temp = df2[["name","artist"]]

df_temp[df_temp.duplicated(keep=False)]

,name,artist
17,Snow (Hey Oh),Red Hot Chili Peppers
18,Dani California,Red Hot Chili Peppers
19,Under the Bridge,Red Hot Chili Peppers
20,The Adventures of Rain Dance Maggie,Red Hot Chili Peppers
23,Bu Dolandırıcılık Neden Engellenmiyor?,Timur Soykan anlattı
...,...,...
593,Placing beams on the roof,#227 The Roof Construction Begins
594,Notching beams,#227 The Roof Construction Begins
595,Bringing the roof beams on site,#227 The Roof Construction Begins
597,Toddler Learning Video - Potty Songs for Toddl...,Potty Training with Ms Rachel
599,Wicked Games (Original Mix),Parra for Cuva

In [14]:
print(df_temp.value_counts())

name                                                                 artist
Outro monologue                                                      Martijn Doolaard                12
ID                                                                   ID                               9
Intro                                                                Martijn Doolaard                 7
Dinner                                                               Martijn Doolaard                 6
Dinner and movie                                                     Martijn Doolaard                 5
                                                                                                     ..
Eating chestnuts                                                     Martijn Doolaard                 1
Cooking chestnuts                                                    Martijn Doolaard                 1
Collecting chestnuts                                                 Martijn Doolaard                 1
Videos for Toddlers - Nursery Rhymes & Kids Songs - Speech Practice  Learn to Talk with Ms Rachel     1
The Kiffness X Alugalug Cat 2.0 (Please Go Away)                     The Kiffness                     1
Name: count, Length: 506, dtype: int64