In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
from data_collection import get_all_recent_tracks
from data_cleaning import clean_tracks

In [3]:
username = input("Enter your last.fm username: ")

data = get_all_recent_tracks(username,10,3)
cleaned_data= clean_tracks(data)
print(len(cleaned_data))

Status code: 200
totalPages = 25969
Status code: 200
Status code: 200
{'artist': {'mbid': '', '#text': 'Korolova'}, 'streamable': '0', 'image': [{'size': 'small', '#text': ''}, {'size': 'medium', '#text': ''}, {'size': 'large', '#text': ''}, {'size': 'extralarge', '#text': ''}], 'mbid': '', 'album': {'mbid': '', '#text': ''}, 'name': 'Captive Soul 100  @ Sagrada Familia, Barcelona', '@attr': {'nowplaying': 'true'}, 'url': 'https://www.last.fm/music/Korolova/_/Captive+Soul+100++@+Sagrada+Familia,+Barcelona'}
{'artist': {'mbid': '', '#text': 'Korolova'}, 'streamable': '0', 'image': [{'size': 'small', '#text': ''}, {'size': 'medium', '#text': ''}, {'size': 'large', '#text': ''}, {'size': 'extralarge', '#text': ''}], 'mbid': '', 'album': {'mbid': '', '#text': ''}, 'name': 'Captive Soul 100  @ Sagrada Familia, Barcelona', '@attr': {'nowplaying': 'true'}, 'url': 'https://www.last.fm/music/Korolova/_/Captive+Soul+100++@+Sagrada+Familia,+Barcelona'}
{'artist': {'mbid': '', '#text': 'Korolova'}, 'streamable': '0', 'image': [{'size': 'small', '#text': ''}, {'size': 'medium', '#text': ''}, {'size': 'large', '#text': ''}, {'size': 'extralarge', '#text': ''}], 'mbid': '', 'album': {'mbid': '', '#text': ''}, 'name': 'Captive Soul 100  @ Sagrada Familia, Barcelona', '@attr': {'nowplaying': 'true'}, 'url': 'https://www.last.fm/music/Korolova/_/Captive+Soul+100++@+Sagrada+Familia,+Barcelona'}
30

In [4]:
df= pd.DataFrame(cleaned_data)
df.head()

,name,artist,album,date,timestamp
0,"Captive Soul 100 @ Sagrada Familia, Barcelona",Korolova,,"30 Sep 2026, 10:44",1790765080
1,Altın Çocuklar ve Kayıp Milyarlar,Timur Soykan anlattı,,"30 Sep 2026, 10:35",1790764536
2,Bu Dolandırıcılık Neden Engellenmiyor?,Timur Soykan anlattı,,"30 Sep 2026, 10:28",1790764117
3,Yeni Türkiye'nin Karanlık Ekonomi Özeti,Timur Soykan anlattı,,"30 Sep 2026, 10:24",1790763878
4,Bu Dolandırıcılık Neden Engellenmiyor?,Timur Soykan anlattı,,"30 Sep 2026, 10:21",1790763683

In [5]:
df.shape

(30, 5)

In [6]:
df.columns

Index(['name', 'artist', 'album', 'date', 'timestamp'], dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       30 non-null     str
 1   artist     30 non-null     str
 2   album      30 non-null     str
 3   date       30 non-null     str
 4   timestamp  30 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

In [8]:
df.dtypes

name         str
artist       str
album        str
date         str
timestamp    str
dtype: object

In [9]:
df.isna().sum()

name         0
artist       0
album        0
date         0
timestamp    0
dtype: int64

In [10]:
df.nunique()

name         27
artist       11
album         1
date         30
timestamp    30
dtype: int64

In [11]:
df["timestamp"].sort_values(ascending=False)

0     1790765080
1     1790764536
2     1790764117
3     1790763878
4     1790763683
5     1790763381
6     1790763344
7     1790762654
8     1790761954
9     1790759945
10    1790759472
11    1790758121
12    1790757664
13    1790757544
14    1790757342
15    1790757210
16    1790757094
17    1790757030
18    1790756966
19    1790756884
20    1790756800
21    1790755703
22    1790752317
23    1790716061
24    1790716005
25    1790715754
26    1790715660
27    1790715595
28    1790715472
29    1790715366
Name: timestamp, dtype: str

In [12]:
df["timestamp"].sort_values(ascending=True)

29    1790715366
28    1790715472
27    1790715595
26    1790715660
25    1790715754
24    1790716005
23    1790716061
22    1790752317
21    1790755703
20    1790756800
19    1790756884
18    1790756966
17    1790757030
16    1790757094
15    1790757210
14    1790757342
13    1790757544
12    1790757664
11    1790758121
10    1790759472
9     1790759945
8     1790761954
7     1790762654
6     1790763344
5     1790763381
4     1790763683
3     1790763878
2     1790764117
1     1790764536
0     1790765080
Name: timestamp, dtype: str

In [13]:
df["artist"].value_counts()

artist
Veritasium                              9
Timur Soykan anlattı                    6
Why Real Feta Cheese Is Disappearing    6
Kirsten Dirksen                         2
Korolova                                1
Aynada Gören Korkuyordu!                1
Red Hot Chili Peppers                   1
Giolì & Assia                           1
Onur Benli                              1
Mahmut Orhan WE2                        1
Mahmut Orhan                            1
Name: count, dtype: int64

In [14]:
df["name"].value_counts()

name
Bu Dolandırıcılık Neden Engellenmiyor?                                         2
Yeni Türkiye'nin Karanlık Ekonomi Özeti                                        2
He dreamed of self-feeding solar house. So he built A-frame greenhouse home    2
Captive Soul 100  @ Sagrada Familia, Barcelona                                 1
Altın Çocuklar ve Kayıp Milyarlar                                              1
Borsa İstanbul'da 900 Milyarlık Vurgun                                         1
Volvo 850R Nasıl Her Şeyi Değiştirdi?                                          1
Snow (Hey Oh)                                                                  1
#DiesisLive @Fjallsarlon Glacier Lagoon, Iceland                               1
The Inside of a Jet Engine                                                     1
Why are jet engines so big?                                                    1
How a jet engine works                                                         1
Impact of outbreak                                                             1
Struggling restaurants                                                         1
Farmer protests                                                                1
Debate over vaccination                                                        1
How feta is made                                                               1
Intro                                                                          1
Arrival at Çeşme                                                               1
Tomorrowland 2026                                                              1
Padel Court 2026 Dubai Full Set                                                1
Real-World Uses and the Ultimate Swing Test                                    1
Engineering Fake Spider Silk                                                   1
Why We Can't Farm Spiders                                                      1
The Nanostructure Behind Spider Silk's Strength                                1
Spider Silk vs Kevlar vs Steel                                                 1
The Strongest Silk on Earth                                                    1
Name: count, dtype: int64

In [15]:
df["album"].value_counts()

album
    30
Name: count, dtype: int64

In [16]:
df

,name,artist,album,date,timestamp
0,"Captive Soul 100 @ Sagrada Familia, Barcelona",Korolova,,"30 Sep 2026, 10:44",1790765080
1,Altın Çocuklar ve Kayıp Milyarlar,Timur Soykan anlattı,,"30 Sep 2026, 10:35",1790764536
2,Bu Dolandırıcılık Neden Engellenmiyor?,Timur Soykan anlattı,,"30 Sep 2026, 10:28",1790764117
3,Yeni Türkiye'nin Karanlık Ekonomi Özeti,Timur Soykan anlattı,,"30 Sep 2026, 10:24",1790763878
4,Bu Dolandırıcılık Neden Engellenmiyor?,Timur Soykan anlattı,,"30 Sep 2026, 10:21",1790763683
5,Yeni Türkiye'nin Karanlık Ekonomi Özeti,Timur Soykan anlattı,,"30 Sep 2026, 10:16",1790763381
6,Borsa İstanbul'da 900 Milyarlık Vurgun,Timur Soykan anlattı,,"30 Sep 2026, 10:15",1790763344
7,Volvo 850R Nasıl Her Şeyi Değiştirdi?,Aynada Gören Korkuyordu!,,"30 Sep 2026, 10:04",1790762654
8,Snow (Hey Oh),Red Hot Chili Peppers,,"30 Sep 2026, 09:52",1790761954
9,"#DiesisLive @Fjallsarlon Glacier Lagoon, Iceland",Giolì & Assia,,"30 Sep 2026, 09:19",1790759945
10,He dreamed of self-feeding solar house. So he ...,Kirsten Dirksen,,"30 Sep 2026, 09:11",1790759472
11,He dreamed of self-feeding solar house. So he ...,Kirsten Dirksen,,"30 Sep 2026, 08:48",1790758121
12,The Inside of a Jet Engine,Veritasium,,"30 Sep 2026, 08:41",1790757664
13,Why are jet engines so big?,Veritasium,,"30 Sep 2026, 08:39",1790757544
14,How a jet engine works,Veritasium,,"30 Sep 2026, 08:35",1790757342
15,Impact of outbreak,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:33",1790757210
16,Struggling restaurants,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:31",1790757094
17,Farmer protests,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:30",1790757030
18,Debate over vaccination,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:29",1790756966
19,How feta is made,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:28",1790756884
20,Intro,Why Real Feta Cheese Is Disappearing,,"30 Sep 2026, 08:26",1790756800
21,Arrival at Çeşme,Onur Benli,,"30 Sep 2026, 08:08",1790755703
22,Tomorrowland 2026,Mahmut Orhan WE2,,"30 Sep 2026, 07:11",1790752317
23,Padel Court 2026 Dubai Full Set,Mahmut Orhan,,"29 Sep 2026, 21:07",1790716061
24,Real-World Uses and the Ultimate Swing Test,Veritasium,,"29 Sep 2026, 21:06",1790716005
25,Engineering Fake Spider Silk,Veritasium,,"29 Sep 2026, 21:02",1790715754
26,Why We Can't Farm Spiders,Veritasium,,"29 Sep 2026, 21:01",1790715660
27,The Nanostructure Behind Spider Silk's Strength,Veritasium,,"29 Sep 2026, 20:59",1790715595
28,Spider Silk vs Kevlar vs Steel,Veritasium,,"29 Sep 2026, 20:57",1790715472
29,The Strongest Silk on Earth,Veritasium,,"29 Sep 2026, 20:56",1790715366

In [17]:
from data_collection import get_track_info
from data_cleaning import clean_track_info

In [18]:


ap= get_track_info("Red Hot Chili Peppers", "Snow (Hey Oh)")
ap

Status code: 200

{'track': {'name': 'Snow (Hey Oh)',
  'mbid': '01e582e4-8cbd-3b84-b0c9-75054f90162a',
  'url': 'https://www.last.fm/music/Red+Hot+Chili+Peppers/_/Snow+(Hey+Oh)',
  'duration': '334000',
  'streamable': {'#text': '0', 'fulltrack': '0'},
  'listeners': '1728547',
  'playcount': '15598360',
  'artist': {'name': 'Red Hot Chili Peppers',
   'mbid': '8bfac288-ccc5-448d-9573-c33ea2aa5c30',
   'url': 'https://www.last.fm/music/Red+Hot+Chili+Peppers'},
  'album': {'artist': 'Red Hot Chili Peppers',
   'title': 'Stadium Arcadium',
   'url': 'https://www.last.fm/music/Red+Hot+Chili+Peppers/Stadium+Arcadium',
   'image': [{'#text': 'https://lastfm-img.freetls.fastly.net/i/u/34s/fb7d1a6c6e5240c48159d08b17ea022b.png',
     'size': 'small'},
    {'#text': 'https://lastfm-img.freetls.fastly.net/i/u/64s/fb7d1a6c6e5240c48159d08b17ea022b.png',
     'size': 'medium'},
    {'#text': 'https://lastfm-img.freetls.fastly.net/i/u/174s/fb7d1a6c6e5240c48159d08b17ea022b.png',
     'size': 'large'},
    {'#text': 'https://lastfm-img.freetls.fastly.net/i/u/300x300/fb7d1a6c6e5240c48159d08b17ea022b.png',
     'size': 'extralarge'}]},
  'toptags': {'tag': [{'name': 'rock', 'url': 'https://www.last.fm/tag/rock'},
    {'name': 'alternative rock',
     'url': 'https://www.last.fm/tag/alternative+rock'},
    {'name': 'alternative', 'url': 'https://www.last.fm/tag/alternative'},
    {'name': 'funk', 'url': 'https://www.last.fm/tag/funk'},
    {'name': 'Red Hot Chili Peppers',
     'url': 'https://www.last.fm/tag/Red+Hot+Chili+Peppers'}]},
  'wiki': {'published': '26 Aug 2008, 16:52',
   'summary': '"Snow (Hey Oh)"  (occasionally stylized as "Snow ((Hey Oh))") is a song by Red Hot Chili Peppers from their 2006 double album, Stadium Arcadium. The song was released as the follow-up single to "Tell Me Baby" on November 20, 2006 and became the band\'s third straight number one hit on the Billboard Modern Rock chart, a spot it held for five straight weeks. The single was their 11th to top that chart, giving the band the all-time record for any artist on that chart, a record they still hold to date and extended in 2016 to 13. <a href="http://www.last.fm/music/Red+Hot+Chili+Peppers/_/Snow+(Hey+Oh)">Read more on Last.fm</a>.',
   'content': '"Snow (Hey Oh)"  (occasionally stylized as "Snow ((Hey Oh))") is a song by Red Hot Chili Peppers from their 2006 double album, Stadium Arcadium. The song was released as the follow-up single to "Tell Me Baby" on November 20, 2006 and became the band\'s third straight number one hit on the Billboard Modern Rock chart, a spot it held for five straight weeks. The single was their 11th to top that chart, giving the band the all-time record for any artist on that chart, a record they still hold to date and extended in 2016 to 13.\nVocalist Anthony Kiedis states that the track is "about surviving, starting fresh. I\'ve made a mess of everything, but I have a blank slate—a canvas of snow—and I get to start over."\nOn June 28, 2012, at the band\'s concert at Goffertpark in Nijmegen, Netherlands during the I\'m with You Tour, the band performed the song for the first time since the end of the Stadium Arcadium Tour nearly five years earlier. <a href="http://www.last.fm/music/Red+Hot+Chili+Peppers/_/Snow+(Hey+Oh)">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}}

In [22]:
af= clean_track_info(ap)

af

{'track_mbid': '01e582e4-8cbd-3b84-b0c9-75054f90162a',
 'duration': '334000',
 'listeners': '1728547',
 'playcount': '15598360',
 'artist_mbid': '8bfac288-ccc5-448d-9573-c33ea2aa5c30',
 'artist': 'Red Hot Chili Peppers',
 'album': 'Stadium Arcadium',
 'tags': ['rock',
  'alternative rock',
  'alternative',
  'funk',
  'Red Hot Chili Peppers']}